apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: Ke7yYOf9F09Zf-3K52pMj4PF4Yb8jznIg3tM9DuH # https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens