---
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflare-tunnel
type: Opaque
stringData:
  token: eyJhIjoiMzc5OTMxYmYyMDUzN2VlNDFlYjE1OGFmZmMzZjgzZDIiLCJ0IjoiZmM4M2Y0ZTctMWNjYS00OTUwLThlYTItNThiOWE4MjQ5YjZjIiwicyI6Ik16ZGpNVFJsWlRFdE56VmxNeTAwWTJFd0xXRTJPV0V0TVdNeVl6RTNOV00zWldJNSJ9