---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: matrix-stack-postgres-data
  namespace: matrix
  # kept intentionally minimal to match other app storage manifests
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi